services:
    far_oneup_flysystem.mount_manager:
        class: League\Flysystem\MountManager

    far_symfony2_upload_bundle.far_symfony2_upload_lib.service:
        class: faparicior\FARSymfony2UploadBundle\Lib\FARSymfony2UploadLib
        arguments:
            - '@translator.default'
            - '@request_stack'
            - '@session'
            - '%far_symfony2_upload.prefix%'
            - '%far_symfony2_upload.temp_path%'
            - '%far_symfony2_upload.temp_path_url_prefix%'
            - '%far_symfony2_upload.thumbnail_directory_prefix%'
            - '%far_symfony2_upload.thumbnail_driver%'
            - '%far_symfony2_upload.thumbnail_size%'
            - '%far_symfony2_upload.max_file_size%'
            - '%far_symfony2_upload.max_files_upload%'
            - '%far_symfony2_upload.file_extensions_allowed%'
            - '%far_symfony2_upload.local_filesystem%'
            - '%far_symfony2_upload.remote_filesystem%'
            - '@oneup_flysystem.mount_manager'