services:
    far_symfony2_upload_bundle.far_symfony2_upload_lib.service:
        class: FARSymfony2UploadBundle\Lib\FARSymfony2UploadLib
        arguments:
            - '@service_container'
            - '@request_stack'
            - '@session'
