parameters:
    far_upload_bundle:
        temp_path: "%kernel.root_dir%/../web/tmp"
        thumbnail_driver: "gd"
        thumbnail_size: "80x80"
        max_file_size: 100000
        max_files_upload: 2
        file_extensions_allowed: ["jpg", "png", "gif"]

services:
    far_symfony2_upload_bundle.far_symfony2_upload_lib.service:
        class: FARSymfony2UploadBundle\Lib\FARSymfony2UploadLib
        arguments:
            - '@service_container'
            - '@request_stack'
            - '@session'
